-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 11:40:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optician
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optician` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Schema optician
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optician` DEFAULT CHARACTER SET utf8 ;
USE `Optician`;

-- -----------------------------------------------------
-- Table `Optician`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`addresses` (
  `addresses_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID for address',
  `addresses_street` VARCHAR(100) NOT NULL COMMENT 'Street name',
  `addresses_street_number` INT(5) NULL COMMENT 'Street Number',
  `addresses_floor` VARCHAR(4) NULL COMMENT 'Floor if applicable',
  `addresses_door` VARCHAR(5) NULL COMMENT 'Door if applicable',
  `addresses_town` VARCHAR(100) NOT NULL COMMENT 'Town of address',
  `addresses_postcode` INT(5) NOT NULL COMMENT 'Post Code of address',
  `addresses_country` VARCHAR(45) NOT NULL COMMENT 'Country of address',
  PRIMARY KEY (`addresses_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Optician`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`vendors` (
  `vendors_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique ID for vendor',
  `vendors_name` VARCHAR(150) NOT NULL COMMENT 'Full name for vendor',
  `vendors_tel` VARCHAR(25) NOT NULL COMMENT 'Telephone number for vendor',
  `vendors_fax` VARCHAR(25) NULL COMMENT 'Fax number for vendor',
  `vendors_nif` VARCHAR(9) NOT NULL COMMENT 'Tax registration number for vendor',
  `addresses_id` INT NOT NULL COMMENT 'ID of the adress of the vendor',
  PRIMARY KEY (`vendors_id`),
  UNIQUE INDEX `vendors_nif_UNIQUE` (`vendors_nif` ASC),
  INDEX `fk_vendors_addresses_idx` (`addresses_id` ASC),
  CONSTRAINT `fk_vendors_address`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `Optician`.`addresses` (`addresses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Optician`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`brands` (
  `brands_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID for the brand',
  `brands_name` VARCHAR(50) NOT NULL,
  `brands_model` VARCHAR(45) NOT NULL COMMENT 'Glasses model  of current brand',
  `vendors_id` INT NOT NULL COMMENT 'ID of the vendor',
  PRIMARY KEY (`brands_id`),
  INDEX `fk_brands_vendors1_idx` (`vendors_id` ASC),
  CONSTRAINT `fk_brands_vendors1`
    FOREIGN KEY (`vendors_id`)
    REFERENCES `Optician`.`vendors` (`vendors_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Optician`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID for each pair of glasses',
  `glasses_prescription_left_eye` VARCHAR(45) NOT NULL COMMENT 'Prescription for the left eye',
  `glasses_prescritpion_right_eye` VARCHAR(45) NOT NULL COMMENT 'Prescription for the right eye',
  `glasses_frame_type` ENUM('rimless', 'rimmed', 'wire-frame') NOT NULL COMMENT 'Choice of frame type',
  `glasses_frame_colour` VARCHAR(45) NOT NULL COMMENT 'Colour of frame',
  `glasses_left_glass_colour` VARCHAR(45) NOT NULL COMMENT 'Colour of left glass',
  `glasses_right_glass_colour` VARCHAR(45) NOT NULL COMMENT 'Colour of right glass',
  `glasses_price` DECIMAL(5, 2) NOT NULL COMMENT 'Price of the pair of glasses',
  `brands_id` INT NOT NULL COMMENT 'ID for brand',
  PRIMARY KEY (`glasses_id`),
  INDEX `fk_glasses_brands1_idx` (`brands_id` ASC),
  CONSTRAINT `fk_glasses_brands1`
    FOREIGN KEY (`brands_id`)
    REFERENCES `Optician`.`brands` (`brands_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Optician`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`customers` (
  `customers_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique ID for customer',
  `customers_name` VARCHAR(150) NOT NULL COMMENT 'Full Name of customer',
  `customers_tel` VARCHAR(45) NOT NULL COMMENT 'Telephone number for customer',
  `customers_email` VARCHAR(150) NOT NULL COMMENT 'Email for customer',
  `customers_reg_date` DATETIME NOT NULL COMMENT 'Customer registration date',
  `addresses_id` INT NOT NULL COMMENT 'ID of the address of the customer',
  `customers_referrer_customers_id` INT NULL COMMENT 'ID of the customer who referred purchasing customer',
  PRIMARY KEY (`customers_id`),
  UNIQUE INDEX `customers_email_UNIQUE` (`customers_email` ASC),
  INDEX `fk_customers_address1_idx` (`addresses_id` ASC),
  INDEX `fk_customers_customers1_idx` (`customers_referrer_customers_id` ASC),
  CONSTRAINT `fk_customers_address1`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `Optician`.`addresses` (`addresses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_customers1`
    FOREIGN KEY (`customers_referrer_customers_id`)
    REFERENCES `Optician`.`customers` (`customers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Optician`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID of staff member',
  `staff_name` VARCHAR(150) NOT NULL COMMENT 'Name of staff member',
  `staff_position` VARCHAR(45) NOT NULL COMMENT 'Name of position within company of staff member',
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Optician`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optician`.`sales` (
  `sales_id` INT NOT NULL  AUTO_INCREMENT COMMENT 'ID of sale',
  `sales_date` DATETIME NOT NULL COMMENT 'Date of sale',
  `sales_invoice_number` INT NOT NULL COMMENT 'Invoice number for sale',
  `glasses_id` INT NOT NULL COMMENT 'ID of glasses sold',
  `customers_id` INT NOT NULL COMMENT 'ID of customer purchasing sale',
  `staff_id` INT NOT NULL COMMENT 'ID of staff member entering sale',
  PRIMARY KEY (`sales_id`),
  UNIQUE INDEX `sales_invoice_UNIQUE` (`sales_invoice_number` ASC),
  INDEX `fk_sales_glasses1_idx` (`glasses_id` ASC),
  INDEX `fk_sales_customers1_idx` (`customers_id` ASC),
  INDEX `fk_sales_staff1_idx` (`staff_id` ASC),
  CONSTRAINT `fk_sales_glasses1`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `Optician`.`glasses` (`glasses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `Optician`.`customers` (`customers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Optician`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
